title: Oniro
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://github.com/Yueqi777/eclipse-oniro4openharmony.github.io.git

aux_links:
  Template Repository: https://github.com/Yueqi777/eclipse-oniro4openharmony.github.io.git
