title: Oniro
description:
theme: just-the-docs
logo: "/assets/images/oniro-logo.png"

url: https://eclipse-oniro4openharmony.github.io

aux_links:
  Template Repository: https://github.com/eclipse-oniro4openharmony/eclipse-oniro4openharmony.github.io
